# vboxmanage list vms
# vagrant package --base vagrant_master_* --output master.box

# Dependency and config checks
require_relative 'vagrant_utilities'

# Configure boxes
Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'
  config.ssh.insert_key = false

  config.vm.define 'chef-server' do |cs|
    cs.vm.network 'private_network', ip: '192.168.123.10'
    cs.vm.hostname = 'chef-server'

    cs.vm.provider 'virtualbox' do |vb|
      vb.cpus = '2'
      vb.memory = '2048'
    end

    cs.vm.provision 'shell', path: 'provision/keys.sh'
    cs.vm.provision 'shell', path: 'provision/bootstrap.sh'
  end


  (1..3).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.network 'private_network', ip: "192.168.123.1#{i}"
      node.vm.hostname = "node#{i}"
      
      node.vm.provider 'virtualbox' do |vb|
        vb.memory = '512'
      end

      node.vm.synced_folder '.', '/vagrant', disabled: true 
      node.vm.provision 'shell', path: 'provision/keys.sh'
      node.vm.provision 'shell', path: 'provision/nodes.sh'
    end
  end

  config.vm.define 'workstation' do |ws|
    ws.vm.network 'private_network', ip: "192.168.123.14"
    ws.vm.hostname = "workstation"

    ws.vm.provider 'virtualbox' do |vb|
      vb.cpus = '1'
      vb.memory = '1024'
    end
    
    ws.vm.provision 'shell', path: 'provision/keys.sh'
    ws.vm.provision 'shell', path: 'provision/workstation.sh'
  end

end
